version: '3.7'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
      - 8443:8443
 #   volumes:
 #     - ./.dbdata:/opt/jboss/keycloak/standalone/data
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  ldap:
    build:
      context: .
      dockerfile: ./ldap/Dockerfile
    ports:
      - 389:389
      - 636:636
  js-console:
    build:
      context: .
      dockerfile: ./js-console/Dockerfile
    ports:
      - 8000:80
